ALTER TABLE `bgpPeers` ADD  `bgpPeer_polled` int(11) NOT NULL,ADD  `bgpPeerInUpdates` int(11) DEFAULT NULL,ADD  `bgpPeerOutUpdates` int(11) DEFAULT NULL,ADD  `bgpPeerInTotalMessages` int(11) DEFAULT NULL,ADD  `bgpPeerOutTotalMessages` int(11) DEFAULT NULL,ADD  `bgpPeerFsmEstablishedTime` int(11) DEFAULT NULL,ADD  `bgpPeerInUpdateElapsedTime` int(11) DEFAULT NULL,ADD  `bgpPeerInUpdates_delta` int(11) DEFAULT NULL,ADD  `bgpPeerInUpdates_rate` int(11) DEFAULT NULL,ADD  `bgpPeerOutUpdates_delta` int(11) DEFAULT NULL,ADD  `bgpPeerOutUpdates_rate` int(11) DEFAULT NULL,ADD  `bgpPeerInTotalMessages_delta` int(11) DEFAULT NULL,ADD  `bgpPeerInTotalMessages_rate` int(11) DEFAULT NULL,ADD  `bgpPeerOutTotalMessages_delta` int(11) DEFAULT NULL,ADD  `bgpPeerOutTotalMessages_rate` int(11) DEFAULT NULL;
UPDATE `bgpPeers` p, `bgpPeers-state` s SET p.`bgpPeer_polled` = s.`bgpPeer_polled`,p.`bgpPeerInUpdates` = s.`bgpPeerInUpdates`,p.`bgpPeerOutUpdates` = s.`bgpPeerOutUpdates`,p.`bgpPeerInTotalMessages` = s.`bgpPeerInTotalMessages`,p.`bgpPeerOutTotalMessages` = s.`bgpPeerOutTotalMessages`,p.`bgpPeerFsmEstablishedTime` = s.`bgpPeerFsmEstablishedTime`,p.`bgpPeerInUpdateElapsedTime` = s.`bgpPeerInUpdateElapsedTime`,p.`bgpPeerInUpdates_delta` = s.`bgpPeerInUpdates_delta`,p.`bgpPeerInUpdates_rate` = s.`bgpPeerInUpdates_rate`,p.`bgpPeerOutUpdates_delta` = s.`bgpPeerOutUpdates_delta`,p.`bgpPeerOutUpdates_rate` = s.`bgpPeerOutUpdates_rate`,p.`bgpPeerInTotalMessages_delta` = s.`bgpPeerInTotalMessages_delta`,p.`bgpPeerInTotalMessages_rate` = s.`bgpPeerInTotalMessages_rate`,p.`bgpPeerOutTotalMessages_delta` = s.`bgpPeerOutTotalMessages_delta`,p.`bgpPeerOutTotalMessages_rate` = s.`bgpPeerOutTotalMessages_rate` WHERE p.`bgpPeer_id` = s.`bgpPeer_id`;
ALTER TABLE `bgpPeers_cbgp` ADD `AcceptedPrefixes` int(11) DEFAULT NULL, ADD `DeniedPrefixes` int(11) DEFAULT NULL, ADD `PrefixAdminLimit` int(11) DEFAULT NULL, ADD `PrefixThreshold` int(11) DEFAULT NULL, ADD `PrefixClearThreshold` int(11) DEFAULT NULL, ADD `AdvertisedPrefixes` int(11) DEFAULT NULL, ADD `SuppressedPrefixes` int(11) DEFAULT NULL, ADD `WithdrawnPrefixes` int(11) DEFAULT NULL;
UPDATE `bgpPeers_cbgp` p, `bgpPeers_cbgp-state` s SET p.`AcceptedPrefixes` = s.`AcceptedPrefixes`,p.`DeniedPrefixes` = s.`DeniedPrefixes`,p.`PrefixAdminLimit` = s.`PrefixAdminLimit`,p.`PrefixThreshold` = s.`PrefixThreshold`,p.`PrefixClearThreshold` = s.`PrefixClearThreshold`,p.`AdvertisedPrefixes` = s.`AdvertisedPrefixes`,p.`SuppressedPrefixes` = s.`SuppressedPrefixes`,p.`WithdrawnPrefixes` = s.`WithdrawnPrefixes` WHERE p.`cbgp_id` = s.`cbgp_id`;
DROP TABLE `bgpPeers-state`;
DROP TABLE `bgpPeers_cbgp-state`;
DROP TABLE `ports-state`;
DROP TABLE `alert_table-state`;

