name: update

on:
  schedule:
    - cron: '00 12 * * *'
  push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for update
        shell: bash
        run: ./.github/scripts/check_update.sh
