name: update

on:
  schedule:
    - cron: '00 12 * * *'
  push: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for update
        run: ./.github/scripts/check_update.sh
        shell: bash
      - name: Update
        if: env.UPDATE_REQUIRED == '1'
        run: ./.github/scripts/update.sh
        shell: bash
      - name: Commit and tag
        if: env.UPDATE_REQUIRED == '1'
        uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          author_name: Daniel Huisman
          author_email: daniel@huisman.me
          message: 'Update to Observium CE ${{ env.LATEST_OBSERVIUM_VERSION }}'
          pull: 'NO-PULL'
          push: true
          tag: 'v${{ env.LATEST_OBSERVIUM_VERSION }}'
      - name: Release
        if: env.UPDATE_REQUIRED == '1'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v${{ env.LATEST_OBSERVIUM_VERSION }}'
          name: 'Observium CE ${{ env.LATEST_OBSERVIUM_VERSION }}'
